square/Valet

README.md
Valet.podspec
Valet/VALSecureEnclaveValet.h
Valet/VALSecureEnclaveValet.m
Valet/VALSynchronizableValet.m
Valet/VALValet.h
Valet/VALValet.m
ValetTests/ValetTests.m

cc @mthole @EricMuller22 @stephencelis 
Bumping the pod spec version to 1.1 since this is a breaking change. Thoughts appreciated!

Make VAL enum values follow Cocoa conventions

---

README.md

cc @dfed @EricMuller22 
quick gorm
Visual Diff:

Updating readme's syntax highlight

---

Valet.podspec
Valet/VALValet.m

cc @EricMuller22 @mikelikespie

Make canAccessKeychain not crash on Mac

---

README.md
Valet.podspec
Valet/VALSecureEnclaveValet.h
Valet/VALSecureEnclaveValet.m
Valet/VALValet.m
ValetTests/ValetTests.m

Verified via manual keychain inspection that this fixes the apple vuln. Would prefer to have an automated test. Looking into it.

Fix Apple Vuln

---

ValetTests/ValetTests.m

cc @EricMuller22 @pwesten 
Explicitly tests the issue brought up by https://github.com/square/Valet/issues/10

Add tests for writing and then reading from different threads with expected results.

---

README.md

cc @EricMuller22 @mikelikespie 
I believe this enumerates all failure cases. Let me know if you can think of others.

Add debugging tips to the README

---

README.md

README CI badge should reflect master

---

.travis.yml

cc @EricMuller22 @rhgills @mtauraso

Use Xcode 6.4 on TravisCI

---

ValetTests/ValetTests.m

Fix stale test variable name

---

README.md

Add minimum requirements

---

Valet.podspec
Valet/VALSecureEnclaveValet.h
Valet/VALSecureEnclaveValet.m
Valet/VALValet.h
Valet/VALValet.m
ValetTests/ValetTests.m

Add a few more AppleDoc style comments (and various other Roomba'ing)

---

Valet.podspec
Valet/VALValet.h

cc @kyleve @EricMuller22 
LMK if you think this is worthy of a minor version bump

Expose unavailable initializer in header

---

Other/ValetDefines.h
Valet.podspec
Valet/VALSecureEnclaveValet.m

Adopt kSecUseAuthenticationUI on iOS 9 and Xcode 7

---

README.md

Final touch to Carthage support

Add Carthage Compatibility badge in README

---

Other/ValetDefines.h
Valet.podspec
Valet.xcodeproj/project.pbxproj
Valet/VALValet.m

Fixes issue #52. Props to @Autoc0diq for discovering and reporting!
cc @EricMuller22

removeObjectForKey:options: returns YES when it fails with -34018

---

README.md

It's simple step-to-step for Carthage use in project.

Include Carthage Text

---

README.md
Valet/VALValet.m

I just spent too long debugging this issue, so hopefully this helps someone else in the future.

Speed up debugging by logging when a known Apple keychain bug is encountered

---

Valet.podspec
Valet/VALSecureEnclaveValet.h
Valet/VALSynchronizableValet.h
Valet/VALValet.m
Valet/VALValet_Protected.h
ValetTests/ValetTests.m

Makes sure that SharedAccessIdentifier Valets properly initialize even when the phone is locked (among other minor fixes).
cc @EricMuller22, @justinseanmartin @kyleve

Shared keychain fix

---

Valet.podspec
Valet/VALValet.m
ValetTests/ValetTests.m

Fixes issue #63 
cc @omarkilani @EricMuller22

Prevent canAccessKeychain from logging to the console. Improve performance in likely case.

---

ValetTouchIDTest/Base.lproj/ValetSecureElementTestMain.storyboard
ValetTouchIDTest/ValetSecureElementTestViewController.m

Add 'Contains Item?' to Touch ID test app

---

Gemfile
Valet.podspec

Should get 2.1.0 capable of being published

Fix pod lint

---

Valet.podspec
Valet/VALSecureEnclaveValet.h
Valet/VALSecureEnclaveValet.m
Valet/VALValet.m
Valet/VALValet_Protected.h
ValetTouchIDTest/ValetSecureElementTestViewController.m

- Valet to 2.2
- Fixes #67 
CC @EricMuller22 @nijindal @nicwise

Differentiate between user cancel and deleted keychain item in VALSecureEnclaveValet

---

Valet/VALValet.m

Missed a few in the last pass. cc @EricMuller22

More aggressive use of const

---

Valet.podspec
Valet/VALSecureEnclaveValet.h
Valet/VALSecureEnclaveValet.m
ValetTouchIDTest/ValetSecureElementTestViewController.m

Addresses #72. See discussion in #73 for reasoning behind this approach.
CC @EricMuller22 @nijindal

Treat authentication failures like a user cancel

---

.travis.yml

@EricMuller22 this works just fine.
Note that this is not a pr against master, but against your develop/3.0 branch
Xcpretty can help with formating.
We can look later into building xctool in safe and efficient way inside Travis.

using xcodebuild

---

Valet/VALValet.h

For consistency with the other accessibility attributes

Comment fix: accessibility -> attribute

---

BUG-BOUNTY.md

Go-live is on 4/11, will merge then

Update BUG-BOUNTY.md to reflect new location

---

.travis.yml

🤞 that this works. Even though we can't run our unit test suite in CI, it'd be great to make sure we at least continue to build.

Attempt to get watchOS target building (not testing) in CI

---

Sources/Internal/Keychain.swift
Sources/Internal/SecItem.swift
Sources/SecureEnclave.swift
Sources/SecureEnclaveValet.swift
Sources/SinglePromptSecureEnclaveValet.swift
Sources/Valet.swift

Takes the learning from https://github.com/square/Valet/pull/152#discussion_r222036403 and applies it, even though we nixed #152

Unify repeated logic

---

README.md
Sources/Internal/Keychain.swift
Tests/ValetTests.swift
Valet.podspec

Addresses #137
cc @MarkVillacampa

Enforce that migration specifies kSecClassGenericPassword to avoid data loss

---

.travis.yml
Scripts/ci.sh

Attempt to run per-platform builds in parallel

---

README.md

Resolves #123
While I was here I also changed `'` to `’` because they look nicer 😂

Add a "Choosing the best Identifier" section to the README

---

README.md

Add Concurrency section to README

---

.gitignore
.travis.yml
Scripts/build.swift
codecov.yml

Resolves #201. I decided to make this change against Valet 4.0 in order to prevent additional merge conflicts.

[Valet 4.0] Set up code coverage

---

README.md
Sources/Valet/SecureEnclave.swift
Sources/Valet/SecureEnclaveValet.swift
Sources/Valet/SinglePromptSecureEnclaveValet.swift
Sources/Valet/Valet.swift
Tests/ValetIntegrationTests/ValetIntegrationTests.swift

This PR is best reviewed commit-by-commit. Some of this work is also on https://github.com/square/Valet/pull/198 – I'm trying to pull some of the pieces off to make that one easier to review.
I added removing a few `return` statements from the code for good measure 😅

[Valet 4.0] Documentation cleanup

---

Sources/Valet/SecureEnclaveValet.swift
Sources/Valet/SinglePromptSecureEnclaveValet.swift
Sources/Valet/Valet.swift

Add availability annotations for renamed methods

---

Sources/Valet/SecureEnclaveAccessControl.swift

Document our ability to unlock with watch

---

Contributing.md

Resolves #234. Whomever reviews this PR, please do go through the instructions and make sure they work for you.

Document how to run watchOS tests locally

---

Contributing.md

Resolves #235. Whomever reviews this PR, please do go through the instructions and make sure they work for you.

Document how to run macOS tests locally

---

Sources/Valet/Accessibility.swift

Correct documentation for Accessibility

---

README.md

Add video tutorial to README

---

README.md
Scripts/build.swift

Add more README badges

---

Gemfile.lock

I've been getting Dependabot emails about needing to update `activesupport`, so here we are.

Run 'bundle update'

---

.github/workflows/ci.yml

We seem to have access to a ton of machines. Let's use them.

Parallelize
