square/Valet

Other/ValetDefines.h
Valet.podspec
Valet.xcodeproj/project.pbxproj
Valet/VALSecureEnclaveValet.m
Valet/VALValet.m
ValetTests/ValetTests.m

Looks like you can write to the keychain on OS X even when you don't have read access (or at least find out that you're trying to add a duplicate item when you don't have access). So instead of cleverly trying to discern the error message behind a SecItemAdd, add the item to the keychain and then see if we can read it back out.
Also did some cleanup to allow VALSecureEnclaveValet to be unit tested.

More robust canAccessKeychain

---

.travis.yml
Valet.podspec
ValetTests/ValetTests.m

SystemUIServer has lived in a stable location for many OS releases, and it is impossible to run your Mac without it.
cc @EricMuller22 @martinmroz @kyleve

Vulnerability test should not rely on Finder

---

Valet.podspec
Valet.xcodeproj/project.pbxproj
Valet.xcodeproj/xcshareddata/xcschemes/Valet Mac.xcscheme
Valet.xcodeproj/xcshareddata/xcschemes/Valet iOS.xcscheme
Valet.xcodeproj/xcshareddata/xcschemes/ValetTouchIDTest.xcscheme
Valet/VALSecureEnclaveValet.h
Valet/VALSecureEnclaveValet.m
Valet/VALSynchronizableValet.m
Valet/VALValet.h
Valet/VALValet.m
ValetTests/Info.plist
ValetTouchIDTest/Info.plist
ValetTouchIDTest/ValetSecureElementTestViewController.m

• Support Xcode 7
• Treat warnings as errors in all targets
• Breaking change: Remove `set*:forKey:prompt:` on VALSecureEnclaveValet since `prompt` will never be used.
• Do not use `NS_ASSUME_NONNULL_*`. Explicitly use `nullable` or `nonnull` to avoid oversight.
• Fix memory leak
• Update to recommended build settings on Xcode 7 (everything still works on Xcode 6.4)
Given the breaking change and support for a brand new Xcode, it made sense to go to v2.0.
cc @EricMuller22 @pwesten @kenwigginton @mthole

Valet to 2.0

---

Valet/VALValet.h

Corrected a few ‘accessible’ misspellings in `VALValet.h`.

Fixed 'accesible' typo

---

Valet/VALSecureEnclaveValet.m

cc @EricMuller22 @Visorox
Bit of a facepalm... was too fast on the previous PR. Plan is to replace the existing pod version so 2.0.2 doesn't crash on Xcode 7 and iOS 8.

Support use of kSecUseNoAuthenticationUI on iOS 8 and Xcode 7

---

ValetTests/ValetTests.m

The Xcode 7 test environment doesn't write kSecAttrAccessGroup or kSecAttrAccessControl values on keychain items, which caused the _sharedAccessGroupPrefix test to fail. _sharedAccessGroupPrefix has been tested on a signed build on iOS 9 so we know it works despite the test failure on Xcode 7. rdar://22395553 has been filed.
While it is highly unfortunate to have to remove a failing test, Apple broke their test environment, and we can't work around it. Fixes #33.
cc @EricMuller22 @shawnwelch

Remove test_sharedAccessGroupPrefix_returnsValidValue.

---

.travis.yml
Valet.xcodeproj/project.pbxproj
Valet.xcodeproj/xcshareddata/xcschemes/Valet-Mac.xcscheme
Valet.xcodeproj/xcshareddata/xcschemes/Valet-iOS.xcscheme
Valet/Info.plist

Closes #35 
This will allow the project to be used by Carthage and other dynamic framework tooling.
Based loosely off of #37 from @EricMuller22, with a couple of changes. This adds two new targets for iOS and OS X that are both dynamic frameworks, compiling the source on their own, rather than including the static library into the dynamic framework.
This also scopes out the headers into their correct visibility, so we shouldn't ever get to see anything we shouldn't, like `mutableBaseQueryWithIdentifier:initializer:accessibility:` or any of it's friends.
Lastly, I renamed the framework files to be `Valet.framework` to better support universal frameworks.

Add framework targets for iOS and OS X

---

Valet.xcodeproj/project.pbxproj

Turning this on prevents the project from building with API's that are not available to app extensions and silences the compiler from warning against linking to this framework.

App extension only API

---

Valet/VALSecureEnclaveValet.m

The current code, with options `[-Werror,-Wtautological-pointer-compare]` set, will produce the following error, as the condition at line 92 of Valet/VALSecureEnclaveValet.m will always evaluate as true:
```
error: comparison of address of 'kSecUseAuthenticationUI' not equal to a null pointer is always true
```
This PR changes the check to test the value of this variable rather than the address of the pointer, allowing my iOS 9 project to compile correctly.

Compare kSecUseAuthenticationUI to nil rather than address of to NULL

---

.travis.yml
Other/ValetDefines.h
README.md
Valet.podspec
Valet.xcodeproj/project.pbxproj
Valet/VALSecureEnclaveValet.h
Valet/VALSecureEnclaveValet.m
Valet/VALSynchronizableValet.m
Valet/VALValet.h
Valet/VALValet.m
Valet/VALValet_Protected.h
ValetTests/ValetTests.m
ValetTouchIDTest/ValetSecureElementTestViewController.m

- VALSecureEnclaveValet can now store keychain elements under different AccessControl rules (UserPresence, TouchIDAnyFingerprint, TouchIDCurrentFingerprintSet, DevicePasscode)
- VALSecureEnclaveValet available on Mac OS 10.11
- Properly made VALValet_Protected.h private under CocoaPods (it was already private via submodules and Carthage)
- Properly made ValetDefines.h private
Fixes #48
cc @EricMuller22 @nicwise

Valet to 2.1

---

Gemfile
Valet.podspec
Valet/VALValet.m
ValetTests/ValetTests.m

[2.2.2] Migration should not fail because `canAccessKeychain` has been called on both Valets

---

Valet.podspec
Valet/VALSecureEnclaveValet.m
Valet/VALSynchronizableValet.m
Valet/VALValet.h
Valet/VALValet.m

If you have the `CLANG_WARN_NULLABLE_TO_NONNULL_CONVERSION` warning enabled, the init/new methods on `Valet` produce the following warning:
```
Valet.framework/Headers/VALValet.h:78:1: Conflicting nullability specifier on return types, 'nullable' conflicts with existing specifier 'nonnull'
Valet.framework/Headers/VALValet.h:79:1: Conflicting nullability specifier on return types, 'nullable' conflicts with existing specifier 'nonnull'
```
Additionally, since `[NSObject init]` is now officially declared as not returning nil, I’ve removed the unneeded nil checks from the existing initializers.

Match nullability specifiers of NSObject initializers

---

.travis.yml
Valet.podspec
Valet/VALSecureEnclaveValet.h
Valet/VALSecureEnclaveValet.m
ValetTests/ValetTests.m

Enables `SecureEnclaveValet`s to use TouchID on macOS!
Built on top of #102. Addresses #100.

Allow TouchID to be use on macOS

---

README.md
Valet.podspec
Valet.xcodeproj/project.pbxproj
Valet/VALSecureEnclaveValet.h
Valet/VALSecureEnclaveValet.m
Valet/VALSecureEnclaveValet_Protected.h
Valet/VALSinglePromptSecureEnclaveValet.h
Valet/VALSinglePromptSecureEnclaveValet.m
Valet/VALValet_Protected.h
Valet/Valet.h
ValetTouchIDTest/Base.lproj/ValetSecureElementTestLaunchScreen.xib
ValetTouchIDTest/Base.lproj/ValetSecureElementTestMain.storyboard
ValetTouchIDTest/ValetTouchIDTestViewController.swift

Fixes #104.
Paired with @EricMuller22 on this. @juantrias, please review
Outstanding work:
@juantrias, it's worth noting we did not find a workaround for the following issue:
1) Authenticate `VALSinglePromptSecureEnclaveValet` with `TouchIDCurrentFingerprintSet`
2) Change fingerprints
-> Values still show up in existing authenticated `VALSinglePromptSecureEnclaveValet` instance.
I think the best way to get around this is to invalidate the context (call `requirePromptOnNextAccess`) when the app enters the background (e.g. fires `UIApplicationDidEnterBackgroundNotification`). We could not determine a way to detect that fingerprints changed... so it's likely best to invalidate the context whenever the fingerprints _could_ change, i.e. when the app is no longer in the foreground. Not ideal, …

Introducing VALSinglePromptSecureEnclaveValet

---

Valet/VALSinglePromptSecureEnclaveValet.m

`[VALSinglePromptSecureEnclaveValet containsObjectForKey]` is returning `YES` after the key has been removed from the Keychain due to TouchID fingerprints changes, after adding or removing a fingerprint. The reason is that the `LAContext` instance kept by `VALSinglePromptSecureEnclaveValet` has the key cached. So, for `containsObjectForKey`, we need to query the Keychain without using this instance, as in regular `VALSecureEnclaveValet`.
Additionally, although this does not affect the functionality, we only need to pass the `LAContext` instance when reading keys from the Keychain, not when adding or removing keys

FIX [VALSinglePromptSecureEnclaveValet containsObjectForKey] on TouchID fingerprints changes 

---

README.md

Now that we're written in Swift, not having `use_frameworks!` in the Podfile would cause our adoptees' builds to fail.

Explicitly mention the 'use_frameworks!' requirement when pulling in Valet via Cocoapods

---

.gitignore
Package.swift
README.md
Sources/SecureEnclave.swift
Sources/SecureEnclaveAccessControl.swift
Sources/SecureEnclaveValet.swift
Sources/SinglePromptSecureEnclaveValet.swift

This was supposedly done with 3.0 according to #89, but I couldn't find any trace of it.
Fixes #89 
Ping @dfed 
If anyone wants to test this about before we merge, you can use the following dependency:
```swift
.package(url: "https://github.com/LinusU/Valet", .branch("swiftpm")),
```

Add support for Swift Package Manager

---

Sources/Internal/Service.swift

Addresses #130.
cc @LinusU @EricMuller22

Assert that the bundle seed ID is not given as an identifier prefix for a shared access group Valet

---

Sources/SinglePromptSecureEnclaveValet.swift
Tests/SinglePromptSecureEnclaveTests.swift
Valet.podspec
Valet.xcodeproj/project.pbxproj

It turns out that `LocalAuthentication` isn't available on tvOS... despite Xcode showing me that it was 🙄. Building for tvOS device (rather than sim) failed due to our `import LocalAuthentication`.
This PR removes `SinglePromptSecureEnclaveValet` from the tvOS target entirely.

Remove SinglePromptSecureEnclaveValet from tvOS target

---

.travis.yml

Unfortunately, I didn't realize that `LocalAuthentication` wasn't supported on tvOS until _after_ I'd merged #126. What turned me onto the oversight was Carthage failing to build.
This PR makes it so that we run Carthage in CI, so that this kind of issue doesn't happen again.
Built on top of #132

Run carthage build in CI

---

Sources/SecureEnclaveValet.swift
Sources/SinglePromptSecureEnclaveValet.swift
Sources/Valet.swift
Tests/SecureEnclaveTests.swift
Tests/SinglePromptSecureEnclaveTests.swift
Tests/ValetTests.swift
Valet.podspec

🔥 
Note to anyone who adopted v3.0-3.1.1:
- If you shipped an app with a `Valet.sharedAccessGroupValet` or `Valet.iCloudSharedAccessGroupValet`, you'll need to take steps to not lose secure data in your next release.
If you released an app with a `Valet.sharedAccessGroupValet`, you'll need to run `Valet.sharedAccessGroupValet(with: yourIdentifier, accessibility: yourAccessibility).migrateObjects(from: Valet.valet(with: yourIdentifier, accessibility: yourAccessibility), removeOnCompletion: true)` before accessing data in your `Valet.sharedAccessGroupValet`
If you released an app with a `Valet.iCloudSharedAccessGroupValet`, you'll need to run `Valet.iCloudSharedAccessGroupValet(with: yourIdentifier, accessibility: yourAccessibility).migrateObjects(from: Valet.iCloudValet(with: …

Create sharedAccessGroup Valet when requested

---

Valet.podspec

This fixes https://github.com/square/Valet/issues/141 using the same strategy as https://github.com/jessesquires/JSQCoreDataKit/pull/99.
There is an error for non-swift projects that use the swift Valet.
It looks like this:
```
The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.
```
Though the suggested workaround was to use Valet 2.0, I believe this fixes the underlying issue.
Reviewers @dfed

Swift Version

---

Sources/Internal/Keychain.swift
Sources/SwiftCompatibility.swift
Valet.podspec
Valet.xcodeproj/project.pbxproj

In Swift 4.1, the version of `flatMap` with the shape
`[T] -> (T -> U?) -> [U]` has been renamed to `compactMap`. By adding this
compatibility shim for Swift versions < 4.1, we can use the new spelling
without losing any backwards compatibility on older Swift versions.
We're also not exporting this, so it has no affect on consuming code. However,
apps that build Valet as a part of their app with Swift 4.1+ will no longer
see warnings about `flatMap` being deprecated.

Add compatibility shim for flatMap rename

---

Sources/SecureEnclaveValet.swift
Sources/SinglePromptSecureEnclaveValet.swift
Sources/Valet.swift

This improves compatibility with Swift 4.2. Fixes #149.

Use -hash instead of -hashValue.

---

Sources/Internal/Keychain.swift
Tests/MacTests.swift
Tests/ValetTests.swift

Why use a nullable data initializer when you could use a non-null one?
Shout out to @icanzilb for opening my eyes to the existence of this initializer.

Avoid using nullable data initializer

---

.gitmodules

This change fixes Carthage. While it's unfortunate to not allow git cloning of submodules to reflect the method of the original clone (i.e. cloning Valet via `ssh` will now clone `XCTest-watchOS` via `https`), it's better to make sure our distribution mechanisms are not broken.
I'm filing an issue with Carthage to see if they can fix the underlying issue. But for now, I'm putting out a fix.
cc @elyasns

Use https for git submodule

---

Sources/SecureEnclaveValet.swift
Sources/SinglePromptSecureEnclaveValet.swift
Sources/Valet.swift
Valet.podspec

Since `init` is already `unavailable`, there's no reason to make the method `private`. Making the method `public` matches `NSObjct`'s declaration of `init`, so... maybe it'll fix #162?

Make unavailable init() public to avoid Swift erroneously declaring other init calls inaccessible

---

.travis.yml
Gemfile
Gemfile.lock
Valet.podspec

_This is taking changes from #174_ 
Adds support for the new CocoaPods 1.7 feature for allowing multiple Swift version support.

Cocoapods Support For Multiple Swift Versions

---

Sources/SecureEnclaveAccessControl.swift

Add support for new-style SecAccessControlCreateFlags constants

---

.travis.yml
Package.swift
Scripts/ci.sh
Sources/Valet/SinglePromptSecureEnclaveValet.swift
Tests/ValetIntegrationTests/ValetIntegrationTests.swift
Tests/ValetTests/SinglePromptSecureEnclaveTests.swift
Valet.xcodeproj/project.pbxproj

This PR gets Valet's Package.swift to build on all platforms, and adds jobs to CI to ensure we don't break this going forward. Resolves #185.
In this PR I also added a bunch of `xcode11` jobs to CI.

Allow Valet's Package.swift to build on all platforms

---

.gitignore
.travis.yml
Scripts/build.swift
Scripts/ci.sh

Our Travis configuration is a pain to maintain because we're putting too much information in it. This PR simplifies the Travis config by moving the different configuration options to a `build.swift` file that can be run on the command line. This swift build script enables us to run builds and tests for multiple platforms in a single, easy-to-read command.
Moving the complex configuration to Swift also enables us to give more semantic meaning to the different configurations passed into `xcodebuild`. It will also make it easier to support Codecov integration.
This work was inspired by https://github.com/dfed/CacheAdvance/pull/19

Simplify .travis.yml configuration by moving complexity to swift CLI

---

.travis.yml

We don't need to build both a `pr` build and a `push` build on every pull request. This PR makes it so we only build `push` builds for `master` and `develop--4.0`. We'll still have PR builds on every PR, but we won't build every PR build twice.
See [Travis's docs](https://docs.travis-ci.com/user/customizing-the-build/#safelisting-or-blocklisting-branches) for more info on this change.

Do not build branch build on every push on PR branches

---

.travis.yml
Scripts/build.swift

This PR enables CI for 3 more platforms that we support.
Note that Xcode 11 installs on Travis do not come with iOS 9, tvOS 9, or watchOS 2. Since our minimum supported Xcode is Xcode 11, we can not run tests against these SDKs in CI.

[Valet 4.0] Enable running CI on iOS 10, tvOS 10, and watchOS 3

---

Sources/Valet/MigrationResult.swift
Tests/ValetIntegrationTests/BackwardsCompatibilityTests/SynchronizableBackwardsCompatibilityTests.swift
Tests/ValetIntegrationTests/BackwardsCompatibilityTests/ValetBackwardsCompatibilityTests.swift
Tests/ValetIntegrationTests/CloudIntegrationTests.swift
Tests/ValetIntegrationTests/ValetIntegrationTests.swift
Tests/ValetTests/ValetTests.swift

A lot of our unit tests were testing a single `valet` configuration when they could have been testing an entire suite. This PR updates a bunch of our tests to expand the matrix of options we test on any run.

Expand test matrix

---

Sources/Valet/Internal/Service.swift
Sources/Valet/Valet.swift
Tests/ValetIntegrationTests/BackwardsCompatibilityTests/ValetBackwardsCompatibilityTests.swift

I realized that the `migrateObjectsFromAlwaysAccessible` methods were not using the correct `service`. This PR fixes that, and writes tests.

[Valet 4.0] Fix migrateObjectsFromAlwaysAccessible methods

---

Sources/Valet/Internal/Keychain.swift
Sources/Valet/SecureEnclave.swift
Sources/Valet/SecureEnclaveValet.swift
Sources/Valet/SinglePromptSecureEnclaveValet.swift
Sources/Valet/Valet.swift
Tests/ValetIntegrationTests/CloudIntegrationTests.swift
Tests/ValetIntegrationTests/MacTests.swift
Tests/ValetIntegrationTests/SecureEnclaveIntegrationTests.swift
Tests/ValetIntegrationTests/SinglePromptSecureEnclaveIntegrationTests.swift
Tests/ValetIntegrationTests/ValetIntegrationTests.swift
ValetTouchIDTest/ValetTouchIDTestViewController.swift

The goal of this PR is to no longer require that we specify `@objc`-specific method names by bringing our method names into [Apple's Swift guidelines for parameter names](https://swift.org/documentation/api-design-guidelines/#parameter-names).
This PR breaks out some of the changes in #198, and also brings the code into alignment with a744a370d77e8fa3a7c188cb3a5797c07a6ada36 (I thought I'd landed this change already 😬).

[Valet 4.0] Standardize method naming

---

Tests/ValetIntegrationTests/MacTests.swift

I think I was too aggressive here. This isn't necessary.

Remove an extraneous testEnvironmentIsSigned check in tests

---

Tests/ValetIntegrationTests/MacTests.swift

I think this test broke in Catalina, ~but I can't be sure –– remember, this test requires a signed environment, so we can't test it in CI~. Update: this test does not require a signed environment and runs on every build.
For some reason, the reference we requested couldn't pull out the vulnerable value from the keychain anymore. I fixed this test by relying on a more-reliable persistent reference.

Fix control list vuln test by using persistent reference

---

.gitignore
.travis.yml
Scripts/build.swift
codecov.yml

This PR is a follow-up to #201 and #202. This way we can compare coverage between `master` and `develop--4.0`.

Enable code coverage on master

---

Sources/Valet/SecureEnclaveValet.swift
Sources/Valet/SinglePromptSecureEnclaveValet.swift
Tests/ValetObjectiveCBridgeTests/VALSecureEnclaveValetTests.m
Tests/ValetObjectiveCBridgeTests/VALSinglePromptSecureEnclaveValetTests.m
Tests/ValetObjectiveCBridgeTests/VALValetTests.m
Valet.xcodeproj/project.pbxproj

This should up our code coverage a good bit. Enables testing that our Objective-C compatibility methods are returning the right objects.
Having Objective-C tests also forces us to get our code comments correct. Nice added bonus 🙂

[Valet 4.0] Add simple Objective-C compatibility layer tests

---

Sources/Valet/Accessibility.swift
Sources/Valet/CloudAccessibility.swift
Sources/Valet/SecureEnclaveAccessControl.swift
Sources/Valet/Valet.swift
Tests/ValetIntegrationTests/MacTests.swift
Tests/ValetIntegrationTests/ValetIntegrationTests.swift
Tests/ValetTests/CloudAccessibilityTests.swift
Tests/ValetTests/ConfigurationTests.swift
Tests/ValetTests/ValetTests.swift

This PR follows up on https://github.com/square/Valet/pull/210#discussion_r369661195

[Valet 4.0] Use CaseIterable instead of allValues where possible

---

README.md
Sources/Valet/Internal/SecItem.swift
Sources/Valet/Internal/Service.swift
Sources/Valet/SecureEnclave.swift
Sources/Valet/SecureEnclaveValet.swift
Sources/Valet/SharedAccessGroupIdentifier.swift
Sources/Valet/SinglePromptSecureEnclaveValet.swift
Sources/Valet/Valet.swift
Tests/ValetIntegrationTests/BackwardsCompatibilityTests/SynchronizableBackwardsCompatibilityTests.swift
Tests/ValetIntegrationTests/BackwardsCompatibilityTests/ValetBackwardsCompatibilityTests.swift
Tests/ValetIntegrationTests/CloudIntegrationTests.swift
Tests/ValetIntegrationTests/MacTests.swift
Tests/ValetIntegrationTests/SecItemTests.swift
Tests/ValetIntegrationTests/SecureEnclaveIntegrationTests.swift
Tests/ValetIntegrationTests/SinglePromptSecureEnclaveIntegrationTests.swift
Tests/ValetIntegrationTests/ValetIntegrationTests.swift
Tests/ValetObjectiveCBridgeTests/VALSecureEnclaveValetTests.m
Tests/ValetObjectiveCBridgeTests/VALSinglePromptSecureEnclaveValetTests.m
Tests/ValetObjectiveCBridgeTests/VALValetTests.m
Tests/ValetTests/SecureEnclaveTests.swift
Tests/ValetTests/SinglePromptSecureEnclaveTests.swift
Tests/ValetTests/ValetTests.swift
Valet.xcodeproj/project.pbxproj

This PR removes the magic that automatically determined the shared access group.
There are two big drivers behind this PR:
1. #197 made this code significantly more complex, since the app ID prefix could no longer always be accessed. This is discussed some in https://github.com/square/Valet/issues/179#issuecomment-575440030.
1. The auto-magical determining of the App ID prefix is non-deterministic on particular iOS versions when an app has gone through the process of [changing its App ID prefix](https://developer.apple.com/library/archive/technotes/tn2311/_index.html). Airbnb found that on iOS 12, the `sharedAccessGroupPrefix` returned the old App ID, where on iOS 13 the `sharedAccessGroupPrefix` returned our new App ID. This non-determinism was only found on App Store signed builds – …

Require that App ID Prefix be explicitly passed into Shared Access Group Valets

---

Package.swift

This line isn't needed. SPM works with the current tag (there is no mention of the `version` field in the current [Package documentation](https://developer.apple.com/documentation/swift_packages/package)).
Shout out to @GeorgeLyon for teaching me that this field was not necessary.

Remove version from Package.swift

---

Sources/Valet/Internal/Keychain.swift
Sources/Valet/MigrationError.swift
Tests/ValetIntegrationTests/ValetIntegrationTests.swift
Tests/ValetTests/MigrationErrorTests.swift

This PR updates the case names in `MigrationError` to be more future-proofed. Previously, we explicitly specified that something was wrong with the query result to be migrated. Now we're committing to something begin wrong in the key/value pairs staged to be migrated.
This PR helps us achieve #226 by making the names of these cases less specific to the current migration API. Since this PR represents a breaking API change, it'd be best to get it in before we release Valet 4.

Rename MigrationError cases with `InQueryResult` to `ToMigrate`

---

README.md

Hopefully this section will help our customers avoid the trap laid bare in #231. I think being more explicit about the Valet sandboxing behavior earlier in the README is a good thing as well. Prior to this PR, the sandboxing behavior was acknowledged but pretty buried.
cc @macrossyun please let me know if this is clear.
I also fixed a copy/paste issue in the README while I was here: we were using `mySecureEnclaveValet` in an example before we'd discussed what a Secure Enclave Valet was.

Create 'Changing an Accessibility Value After Persisting Data' section in README

---

Valet.xcodeproj/project.pbxproj

This PR updates `XCTest-watchOS` to point at https://github.com/dfed/XCTest-watchOS/pull/4, and adds all of our test files to the watchOS app. All tests pass:
```
Executing KeychainErrorTests.test_description_createsHumanReadableDescription
- PASSED: KeychainErrorTests.test_description_createsHumanReadableDescription
Executing KeychainErrorTests.test_initStatus_createsNotFoundErrorFrom_errSecItemNotFound
- PASSED: KeychainErrorTests.test_initStatus_createsNotFoundErrorFrom_errSecItemNotFound
Executing KeychainErrorTests.test_initStatus_createsUserCancelledFrom_errSecUserCanceled
- PASSED: KeychainErrorTests.test_initStatus_createsUserCancelledFrom_errSecUserCanceled
Executing KeychainErrorTests.test_initStatus_createsUserCancelledFrom_errSecAuthFailed
- PASSED: …
```

Get watchOS tests running locally

---

README.md
Sources/Valet/Internal/Keychain.swift
Sources/Valet/MigratableKeyValuePair.swift
Sources/Valet/Valet.swift
Tests/ValetIntegrationTests/KeychainIntegrationTests.swift
Tests/ValetIntegrationTests/ValetIntegrationTests.swift
Tests/ValetObjectiveCBridgeTests/VALValetTests.m
Valet.xcodeproj/project.pbxproj

This PR resolves #226 by adding the ability to `compactMap` over key:value pairs as they are being migrated.
I do not intend to merge this PR prior to the release of Valet 4.0.

Add ability to transform values on migrate

---

README.md
Sources/Valet/SecureEnclaveValet.swift
Sources/Valet/SinglePromptSecureEnclaveValet.swift
Sources/Valet/Valet.swift

See [this file](https://opensource.apple.com/source/Security/Security-59306.120.7/keychain/securityd/SecDbKeychainItemV7.m) for the constant. Follow up to #246 and #247.
Given that we have the known upper desired limit of keychain secret size (thank you @KhaosT!), I think it's reasonable for us to create a new `KeychainError` case `valueTooLarge`, and check that the entered data isn't above that limit before interacting with the `securityd`. If and when we do that, we'd want to change this `/// - Important` to a `/// - Precondition`.
Open to someone putting out a PR that does that (or I can get to it at a future date). We'd want to do this check [within `Keychain`'s `setObject(_:forKey:options:)`](https://github.com/square/Valet/blob/ec9c2a3999d2c3e2626c134b0155395ce1c58ce6/Sources/Valet/I …

Recommend that data should be no longer than REASONABLE_SECRET_DATA_SIZE

---

Sources/Valet/Accessibility.swift
Sources/Valet/CloudAccessibility.swift

Attempts to resolve #257. The conditions that lead to data under `afterFirstUnlock` being inaccessible is more clear than the conditions that lead to the data being accessible, so I inverted the sentence a bit. I liked the consistency brought by always stating when the data was accessible, but I was having trouble finding a way to word that clearly given the feedback we received in #257. Open to feedback or alternative wording suggestions!
Note that I didn't change the documentation in `VALLegacyValet`, since that file is no longer public and utilized only by our test suite.
cc @sergstav

Make afterFirstUnlock documentation more clear

---

Sources/Valet/SinglePromptSecureEnclaveValet.swift
Tests/ValetIntegrationTests/SinglePromptSecureEnclaveIntegrationTests.swift
Tests/ValetObjectiveCBridgeTests/VALSinglePromptSecureEnclaveValetTests.m
Tests/ValetTests/SinglePromptSecureEnclaveTests.swift

LAContext is not available in tvOS, but for some reason it was compiling in older Xcode versions.

Remove SinglePromptSecureEnclaveValet from tvOS targets

---

Tests/ValetIntegrationTests/ValetIntegrationTests.swift
Valet.xcodeproj/project.pbxproj
Valet.xcodeproj/xcshareddata/xcschemes/Valet watchOS Test Host App Extension.xcscheme
Valet.xcodeproj/xcshareddata/xcschemes/Valet watchOS Test Host App.xcscheme

As title. I also did some build configuration cleanup while I was here to ensure that building tests to device works on Xcode 13. Best reviewed commit-by-commit.

Include newer iOS and tvOS simulator checks in 'testEnvironmentSupportsWhenPasscodeSet()'

---

.github/workflows/ci.yml
Scripts/build.swift
Scripts/github/prepare-simulators.sh

macOS 10.15 [is no longer supported by Github Actions](https://github.com/actions/runner-images/blob/main/images/macos/macos-10.15-Readme.md). So instead let's run CI on macOS 11 and macOS 12.

Get CI running on macOS 11 and 12

---

.github/workflows/ci.yml

As title. `xcversion` was bugging out [elsewhere](https://github.com/dfed/CacheAdvance/pull/65) so I'm removing its use here.

Use xcode-select instead of xcversion

---

.github/workflows/ci.yml
Scripts/build.swift
Sources/LegacyValet/VALLegacySecureEnclaveValet.m
Sources/Valet/SinglePromptSecureEnclaveValet.swift
Tests/ValetIntegrationTests/BackwardsCompatibilityTests/SecureEnclaveBackwardsCompatibilityTests.swift
Tests/ValetIntegrationTests/BackwardsCompatibilityTests/SinglePromptSecureEnclaveBackwardsCompatibilityTests.swift
Tests/ValetIntegrationTests/BackwardsCompatibilityTests/SynchronizableBackwardsCompatibilityTests.swift
Tests/ValetIntegrationTests/BackwardsCompatibilityTests/ValetBackwardsCompatibilityTests.swift
Tests/ValetIntegrationTests/CloudIntegrationTests.swift
Tests/ValetIntegrationTests/KeychainIntegrationTests.swift
Tests/ValetIntegrationTests/MacTests.swift
Tests/ValetIntegrationTests/SecureEnclaveIntegrationTests.swift
Tests/ValetIntegrationTests/SinglePromptSecureEnclaveIntegrationTests.swift
Tests/ValetIntegrationTests/ValetIntegrationTests.swift
Valet.xcodeproj/xcshareddata/xcschemes/Valet iOS.xcscheme
Valet.xcodeproj/xcshareddata/xcschemes/Valet watchOS Test Host App Extension.xcscheme
Valet.xcodeproj/xcshareddata/xcschemes/Valet watchOS Test Host App.xcscheme

This PR starts modernizing the project's CI integration, starting with updating the platform support.

Modernize CI

---

Gemfile
Gemfile.lock
README.md
Sources/Valet/Internal/Service.swift
Sources/Valet/SecureEnclave.swift
Sources/Valet/SecureEnclaveValet.swift
Sources/Valet/SinglePromptSecureEnclaveValet.swift
Sources/Valet/Valet.swift
Tests/ValetIntegrationTests/BackwardsCompatibilityTests/ValetBackwardsCompatibilityTests.swift
Tests/ValetIntegrationTests/SecureEnclaveIntegrationTests.swift
Tests/ValetIntegrationTests/SinglePromptSecureEnclaveIntegrationTests.swift
Tests/ValetIntegrationTests/ValetIntegrationTests.swift
Tests/ValetTests/SecureEnclaveTests.swift
Tests/ValetTests/SinglePromptSecureEnclaveTests.swift
Tests/ValetTests/ValetTests.swift
Valet iOS Test Host App/Valet iOS Test Host App.entitlements
Valet macOS Test Host App/Valet_macOS_Test_Host_App.entitlements
Valet tvOS Test Host App/Valet tvOS Test Host App.entitlements
Valet watchOS Test Host App Extension/Valet watchOS Test Host App Extension.entitlements
Valet.podspec
Valet.xcodeproj/xcshareddata/xcschemes/Valet watchOS Test Host App Extension.xcscheme
Valet.xcodeproj/xcshareddata/xcschemes/Valet watchOS Test Host App.xcscheme

Previously, the shared access group identifier was used for both the access group itself, as well as the uniqueness identifier for the given Valet. This adds an optional additional `identifier` parameter that can be specified when creating a shared access group Valet. The identifier adds an additional element of uniqueness, so two Valets with the same shared access group can exist, and their data will not overlap, so long as they have different identifiers.
The default for this value is `nil`, which keeps the existing behavior for full backward compatibility.

Add support for multiple Valets within the same access group

---

.github/workflows/ci.yml

As title. Per https://github.com/actions/runner-images/issues/7687#issuecomment-1620396057 it's time to add this back.

Add iOS 13 back to CI

---

.github/workflows/ci.yml
Package.swift
README.md
Scripts/build.swift
Sources/Valet/Accessibility.swift
Sources/Valet/CloudAccessibility.swift
Sources/Valet/Identifier.swift
Sources/Valet/Internal/Configuration.swift
Sources/Valet/Internal/Service.swift
Sources/Valet/KeychainError.swift
Sources/Valet/MigrationError.swift
Sources/Valet/SecureEnclave.swift
Sources/Valet/SecureEnclaveAccessControl.swift
Sources/Valet/SecureEnclaveValet.swift
Sources/Valet/SharedGroupIdentifier.swift
Sources/Valet/SinglePromptSecureEnclaveValet.swift
Sources/Valet/Valet.swift
Valet.podspec

We've been thread-safe since v1. We just hadn't told the compiler this fact yet.
This PR won't compile on Xcode 12.4 or prior, and we currently support back to Xcode 11. We therefore have two options:
1. Drop support for these long-useless Xcode builds in a feature version. This is somewhat reasonable since you haven't been able to ship to the App Store with these versions for years. We also haven't run these old versions of Xcode in CI in many years.
1. Roll a breaking change. I'd prefer to do that with more thought though: if we want a breaking change it'll be a bit before this can land + be released.
I'd be curious to hear from @pwesten and friends how they'd like to approach this before I go and update the README on this PR.

Make core types Sendable and @unchecked Sendable

---

.github/workflows/ci.yml
Scripts/build.swift

It builds. :shipit: 
Also updated to use macOS 14 and Xcode 15 when available, and also upgraded to `checkout@v4`.
Edit: No, it doesn't build. But #313 fixes that.

Get CI running Xcode 15

---

.github/workflows/ci.yml
README.md
Scripts/build.swift
Tests/ValetIntegrationTests/ValetIntegrationTests.swift
Valet watchOS Test Host App Watch App/Assets.xcassets/AccentColor.colorset/Contents.json
Valet watchOS Test Host App Watch App/Assets.xcassets/AppIcon.appiconset/Contents.json
Valet watchOS Test Host App Watch App/Assets.xcassets/Contents.json
Valet watchOS Test Host App Watch App/ContentView.swift
Valet watchOS Test Host App Watch App/Preview Content/Preview Assets.xcassets/Contents.json
Valet watchOS Test Host App Watch App/Valet_watchOS_Test_Host_AppApp.swift
Valet.xcodeproj/project.pbxproj
Valet.xcodeproj/xcshareddata/xcschemes/Valet watchOS Test Host App Extension.xcscheme

Uh oh.
This regressed in [#300](https://github.com/square/Valet/pull/300/commits/b93e01d956ff8a140e2311f34c3b5a84468b06de)

Actually fail CI when tests fail

---

.github/workflows/ci.yml
.gitmodules
README.md
Scripts/build.swift
Tests/ValetIntegrationTests/SecureEnclaveIntegrationTests.swift
Tests/ValetIntegrationTests/SinglePromptSecureEnclaveIntegrationTests.swift
Tests/ValetIntegrationTests/ValetIntegrationTests.swift
Valet watchOS Test Host App Extension/InterfaceController.swift
Valet watchOS Test Host App Watch App/Assets.xcassets/AccentColor.colorset/Contents.json
Valet watchOS Test Host App Watch App/Assets.xcassets/AppIcon.appiconset/Contents.json
Valet watchOS Test Host App Watch App/Assets.xcassets/Contents.json
Valet watchOS Test Host App Watch App/ContentView.swift
Valet watchOS Test Host App Watch App/Preview Content/Preview Assets.xcassets/Contents.json
Valet watchOS Test Host App Watch App/Valet_watchOS_Test_Host_AppApp.swift
Valet.xcodeproj/project.pbxproj
Valet.xcodeproj/xcshareddata/xcschemes/Valet watchOS Test Host App Extension.xcscheme
Valet.xcodeproj/xcshareddata/xcschemes/Valet watchOS.xcscheme

Resolves #128.
We don't have coverage for all watchOS versions, but it's better than what we had.
A good amount of work is from #312 and #313 – it's worth reviewing my comments there.

Get watchOS tests running in CI

---

Scripts/upload-coverage-reports.sh

I think this should just work now? Pretty sure this deleted code was a holdover from back when watchOS didn't have a unit test target.

Upload coverage for watchOS

---

.github/workflows/ci.yml

The old link validator is now deprecated

Update readme validator

---

.github/workflows/ci.yml

@pwesten had a good idea to run CI on some regular cadence so that we can catch CI bitrot (and Github Actions deprecations) sooner rather than later. This PR creates a simple&naive implementation of this: it schedules CI to run once a week.
Ideally we'd only run this if no other CI has run that week. But that's more work – it'd likely involve hitting Github's API endpoint to determine when the last build was, which isn't super hard (ChatGPT can probably script that pretty quickly), but figured we'd start simple.
Happy to change the cadence, but I already had a repo with a weekly job so I just borrowed that code without much thought.

Test CI weekly

---

Scripts/build.swift

Use executableURL in build script

---

Sources/Valet/Identifier.swift
Sources/Valet/Internal/Configuration.swift
Sources/Valet/Internal/Keychain.swift
Sources/Valet/Internal/SecItem.swift
Sources/Valet/Internal/Service.swift
Sources/Valet/Internal/WeakStorage.swift
Sources/Valet/MigratableKeyValuePair.swift
Sources/Valet/SecureEnclave.swift
Sources/Valet/SecureEnclaveAccessControl.swift
Sources/Valet/SecureEnclaveValet.swift
Sources/Valet/SharedGroupIdentifier.swift
Sources/Valet/SinglePromptSecureEnclaveValet.swift
Sources/Valet/Valet.swift
Tests/ValetIntegrationTests/ValetIntegrationTests.swift

Remove "internal" access modifiers from code #339

Code cleanup, Remove "internal" access modifiers from code
